In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('C:/Users/Ritika/Downloads/Data set/Customers.csv')

In [8]:
df.head()

,Customer_ID,Age,Gender,Item,Category,Amount,Location,Size,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Payment_Method,Purchase_Frequency
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Customer_ID          3900 non-null   int64
 1   Age                  3900 non-null   int64
 2   Gender               3900 non-null   object
 3   Item                 3900 non-null   object
 4   Category             3900 non-null   object
 5   Amount               3900 non-null   int64
 6   Location             3900 non-null   object
 7   Size                 3900 non-null   object
 8   Color                3900 non-null   object
 9   Season               3900 non-null   object
 10  Review_Rating        3863 non-null   float64
 11  Subscription_Status  3900 non-null   object
 12  Shipping_Type        3900 non-null   object
 13  Discount_Applied     3900 non-null   object
 14  Promo_Code_Used      3900 non-null   object
 15  Previous_Purchases   3900 non-null   int64
 16  Payment_Method       3900 non-null   object
 17  Purchase_Frequency   3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [10]:
df.describe()

,Customer_ID,Age,Amount,Review_Rating,Previous_Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [12]:
df.isnull().sum()

Customer_ID             0
Age                     0
Gender                  0
Item                    0
Category                0
Amount                  0
Location                0
Size                    0
Color                   0
Season                  0
Review_Rating          37
Subscription_Status     0
Shipping_Type           0
Discount_Applied        0
Promo_Code_Used         0
Previous_Purchases      0
Payment_Method          0
Purchase_Frequency      0
dtype: int64

In [13]:
df['Review_Rating'] = df.groupby('Category')['Review_Rating'].transform(lambda x: x.fillna(x.median()))

In [14]:
df.isnull().sum()

Customer_ID            0
Age                    0
Gender                 0
Item                   0
Category               0
Amount                 0
Location               0
Size                   0
Color                  0
Season                 0
Review_Rating          0
Subscription_Status    0
Shipping_Type          0
Discount_Applied       0
Promo_Code_Used        0
Previous_Purchases     0
Payment_Method         0
Purchase_Frequency     0
dtype: int64

In [15]:
df.columns = df.columns.str.lower()

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item', 'category', 'amount',
       'location', 'size', 'color', 'season', 'review_rating',
       'subscription_status', 'shipping_type', 'discount_applied',
       'promo_code_used', 'previous_purchases', 'payment_method',
       'purchase_frequency'],
      dtype='object')

In [23]:
labels = ['Young Adult', 'Adult', 'Senior','Middle-aged']

In [24]:
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [26]:
df[['age','age_group']].head()

   age    age_group
0   55       Senior
1   19  Young Adult
2   50       Senior
3   21  Young Adult
4   45       Senior

In [27]:
df[['discount_applied','promo_code_used']]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [32]:
(df['discount_applied'] == df['promo_code_used']).all()

True

In [37]:
df = df.drop('discount_applied',axis = 1)